"""Fix email unique constraint

Revision ID: 099bf1f0018d
Revises: 68b56b009282
Create Date: 2024-10-31 21:38:24.162140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099bf1f0018d'
down_revision = '68b56b009282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('unique_email_when_not_null', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('unique_email_when_not_null', postgresql_where=sa.text('email IS NOT NULL'))

    # ### end Alembic commands ###
