"""Add assessment questionnaire system models

Revision ID: 623f1adba55d
Revises: ae1009027bf8
Create Date: 2024-11-13 15:13:12.388543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623f1adba55d'
down_revision = 'ae1009027bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('tool_type', sa.String(length=50), nullable=False),
    sa.Column('scoring_logic', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_tool', schema=None) as batch_op:
        batch_op.create_index('idx_assessment_tool_name', ['name'], unique=False)
        batch_op.create_index('idx_assessment_tool_type', ['tool_type'], unique=False)

    op.create_table('assessment_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['assessment_tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.create_index('idx_assessment_question_tool', ['tool_id', 'order'], unique=False)

    op.create_table('assessment_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('assessor_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['assessment_tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.create_index('idx_assessment_result_date', ['assessment_date'], unique=False)
        batch_op.create_index('idx_assessment_result_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_assessment_result_tool', ['tool_id'], unique=False)

    op.create_table('assessment_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_value', sa.String(length=500), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_question.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['assessment_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_response', schema=None) as batch_op:
        batch_op.create_index('idx_assessment_response_question', ['question_id'], unique=False)
        batch_op.create_index('idx_assessment_response_result', ['result_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action_type', ['action', 'resource_type'], unique=False)
        batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('condition', schema=None) as batch_op:
        batch_op.create_index('idx_condition_code', ['code'], unique=False)
        batch_op.create_index('idx_condition_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_condition_status', ['clinical_status'], unique=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('idx_document_content', ['content'], unique=False)
        batch_op.create_index('idx_document_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_document_title', ['title'], unique=False)

    with op.batch_alter_table('icd10_code', schema=None) as batch_op:
        batch_op.create_index('idx_icd10_code', ['code'], unique=False)
        batch_op.create_index('idx_icd10_description', ['description'], unique=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index('idx_patient_identifier', ['identifier'], unique=False)
        batch_op.create_index('idx_patient_location', ['city', 'state', 'country'], unique=False)
        batch_op.create_index('idx_patient_name', ['family_name', 'given_name'], unique=False)

    with op.batch_alter_table('patient_identifier', schema=None) as batch_op:
        batch_op.create_index('idx_patient_identifier_type_value', ['identifier_type', 'identifier_value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_identifier', schema=None) as batch_op:
        batch_op.drop_index('idx_patient_identifier_type_value')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index('idx_patient_name')
        batch_op.drop_index('idx_patient_location')
        batch_op.drop_index('idx_patient_identifier')

    with op.batch_alter_table('icd10_code', schema=None) as batch_op:
        batch_op.drop_index('idx_icd10_description')
        batch_op.drop_index('idx_icd10_code')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('idx_document_title')
        batch_op.drop_index('idx_document_patient')
        batch_op.drop_index('idx_document_content')

    with op.batch_alter_table('condition', schema=None) as batch_op:
        batch_op.drop_index('idx_condition_status')
        batch_op.drop_index('idx_condition_patient')
        batch_op.drop_index('idx_condition_code')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_timestamp')
        batch_op.drop_index('idx_audit_action_type')

    with op.batch_alter_table('assessment_response', schema=None) as batch_op:
        batch_op.drop_index('idx_assessment_response_result')
        batch_op.drop_index('idx_assessment_response_question')

    op.drop_table('assessment_response')
    with op.batch_alter_table('assessment_result', schema=None) as batch_op:
        batch_op.drop_index('idx_assessment_result_tool')
        batch_op.drop_index('idx_assessment_result_patient')
        batch_op.drop_index('idx_assessment_result_date')

    op.drop_table('assessment_result')
    with op.batch_alter_table('assessment_question', schema=None) as batch_op:
        batch_op.drop_index('idx_assessment_question_tool')

    op.drop_table('assessment_question')
    with op.batch_alter_table('assessment_tool', schema=None) as batch_op:
        batch_op.drop_index('idx_assessment_tool_type')
        batch_op.drop_index('idx_assessment_tool_name')

    op.drop_table('assessment_tool')
    # ### end Alembic commands ###
