"""Add before_value and after_value to AuditLog

Revision ID: ae1009027bf8
Revises: bad30b5187a1
Create Date: 2024-11-02 14:47:59.760827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1009027bf8'
down_revision = 'bad30b5187a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_value', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('after_value', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('after_value')
        batch_op.drop_column('before_value')

    # ### end Alembic commands ###
