"""Add Condition model

Revision ID: bad30b5187a1
Revises: 1c58128576da
Create Date: 2024-11-01 13:13:03.453637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad30b5187a1'
down_revision = '1c58128576da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=True),
    sa.Column('clinical_status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('code_system', sa.String(length=100), nullable=True),
    sa.Column('body_site', sa.String(length=100), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('onset_string', sa.String(length=200), nullable=True),
    sa.Column('abatement_date', sa.Date(), nullable=True),
    sa.Column('abatement_string', sa.String(length=200), nullable=True),
    sa.Column('recorded_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition')
    # ### end Alembic commands ###
